version: '2.2'

services:
  postgres:
    container_name: scannerbot_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: scannerbot_dev
      POSTGRESQL_FSYNC: "off"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "55432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: scannerbot_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: